# 数据库连接配置文件（YAML）

connections:
  # ── UAT 环境 ────────────────────────────────────────
  - name: UAT 数据库
    env: UAT
    host: localhost
    port: 1433
    database: testDB
    username: Alen.Li
    password: password123

  # ── PROD 环境 ───────────────────────────────────────
  - name:  PROD 数据库
    env: PROD
    host: localhost\prod
    port: 1433
    database: testDB
    username: Alen.Li
    password: password123
